# opencraft.yml is the main configuration file for a Opencraft server
# It contains everything from server.properties and bukkit.yml in a
# normal CraftBukkit installation.

opencraft:
    collector: false
    policy: chunk
    broker:
        type: read-write
        async: false
        threads: 16
        capacity: 2147483647
        channel: unsafe
        host: localhost
        port: 0
        username: ''
        password: ''
        virtualHost: ''
server:
    ip: ''
    port: 25565
    name: Opencraft Server
    log-file: logs/log-%D.txt
    online-mode: false
    max-players: 20000
    whitelisted: false
    motd: An Opencraft server
    shutdown-message: Server shutting down.
    allow-client-mods: true
    dns: []
    snooper-enabled: false
    prevent-proxy-connections: true
console:
    use-jline: true
    prompt: '> '
    date-format: HH:mm:ss
    log-date-format: yyyy/MM/dd HH:mm:ss
game:
    gamemode: CREATIVE
    gamemode-force: true
    difficulty: NORMAL
    hardcore: false
    pvp: true
    max-build-height: 256
    announce-achievements: true
    allow-flight: false
    command-blocks: false
    resource-pack: ''
    resource-pack-hash: ''
creatures:
    enable:
        monsters: true
        animals: true
        npcs: true
    limit:
        monsters: 70
        animals: 15
        water: 5
        ambient: 15
    ticks:
        monsters: 1
        animal: 400
folders:
    plugins: plugins
    update: update
    worlds: worlds
    libraries: lib
files:
    permissions: permissions.yml
    commands: commands.yml
    help: help.yml
advanced:
    connection-throttle: 4000
    idle-timeout: 0
    warn-on-overload: true
    exact-login-location: false
    plugin-profiling: false
    deprecated-verbose: 'false'
    compression-threshold: 256
    proxy-support: false
    player-sample-count: 12
    graphics-compute:
        enable: false
        use-any-device: false
    region-file:
        cache-size: 256
        compression: true
    profile-lookup-timeout: 5
    suggest-player-name-when-null-tab-completions: true
extras:
    query-enabled: false
    query-port: 25614
    query-plugins: true
    rcon-enabled: false
    rcon-password: opencraft
    rcon-port: 25575
    rcon-colors: true
world:
    name: world
    seed: 9112908162034899261
    level-type: DEFAULT
    spawn-radius: 16
    view-distance: 8
    gen-structures: true
    allow-nether: true
    allow-end: true
    keep-spawn-loaded: true
    populate-anchored-chunks: true
    classic-style-water: false
    disable-generation: false
libraries:
    checksum-validation: true
    repository-url: https://repo1.maven.org/maven2/
    download-attempts: 2
    compatibility-bundle: CRAFTBUKKIT
    list: []
